server:
  port: 8080

spring:
  application:
    name: flux-export-sample
# FluxExport Config
flux-export:
  storage:
    local:
      path: ./exports
      url-prefix: http://localhost:8080/files/

# Logging Config
logging:
  level:
    com.flux.export: DEBUG
